# fly.toml app configuration file generated for mercadona-app on 2023-11-16T20:28:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mercadona-app"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
